### ISSUE TITLE
High Memory Foot Print and Inference Time

### ISSUE THREAD

**Issue by Manas-Embold** [facebookresearch/aroma-paper-artifacts#7]
The paper says "Aroma takes 1.6seconds to create recommendations for a query code snippet on a 24-core CPU." 
Question 1: Does this include time to load vocab.pkl file, feature.json file and tfidf.pkl file ?

However, memory footprint of the artifact in this repository is very high.
Following function takes a lot of RAM. 
https://github.com/facebookresearch/aroma-paper-artifacts/blob/e8d8beeb99255d8929874c156fd65aac74d21508/reference/src/main/python/similar.py#L361

Question 2: Can we reduce it with removing duplicate function records (is it already done ?)or by yielding one record at a time instead of loading all records in a list.

Question 3: I am trying this on some 20-40 apache repositories, and even 25GB RAM is also not enough for this. (process gets killed while running above function (read_all_records() function) during featurize asts step)

**Comment by frank-lsf** [comment]
Hi Manas,

1. The 1.6 seconds does not include time to load the corpus files. Also, in the experiments we run an optimized version of Aroma in C++. The code in this repository is for prototyping and runs considerably slower.
2. Memory usage is indeed high in this prototype since a) we load all the records in memory for the search, and b) Python objects have considerable memory overhead.
3. How many functions are there in your repositories? The featurization step does require a lot of memory since it loads all the trees into memory. Perhaps you can find higher-memory servers on AWS (such as the r5 series)? If not, you should be able to modify the code to process the trees in a streaming fashion. The algorithm does not technically require all the trees to be in memory; only the feature map needs to be in memory.

**Comment by Manas-Embold** [comment]
Thank you,
That was really helpful.
I have around 5 lakh (half million) functions in my repository
