### ISSUE TITLE
Is there any constraint on Query 

### ISSUE THREAD

**Issue by Manas-Embold** [facebookresearch/aroma-paper-artifacts#8]
When i pass a query most of the time i don't get recommendations.

1. Is it due to less training data or
2. Are there any constraint that query should be parsable java statements (used by some parser in code)
3. Does the program expects query to be a valid java class / java method without any syntax error (i.e, parsable) ?

**Comment by frank-lsf** [comment]
Yes, the query needs to be parsable Java code. This is because the parser has undefined behavior when fed with partial code.

A simple test would be finding a method in your corpus, and use its first line as query, see if you can get recommendations of the rest of the method.

If you want to dig in, you can print out the features derived from the query code and see if they make sense. You can also try reducing the recommendation thresholds so you get more matches.

**Comment by Manas-Embold** [comment]
Thank you.
